# Generated by Django 5.1.6 on 2025-05-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_teammember_alter_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
