# Generated by Django 5.1.6 on 2025-05-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutco'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutco',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
